setwd("C:/Users/Debanjan/Desktop/Coursera")
fulldata <- read.csv("household_power_consumption.txt", head=TRUE, sep=";", na.strings="?")
Date <- as.Date(fulldata$Date, "%d/%m/%Y")
data <- cbind(Date, fulldata)
data <- data[,-2]
data201 <- subset(data, Date == "2007-02-01")
data202 <- subset(data, Date == "2007-02-02")
finaldata <- rbind(data201, data202)
datetime <- as.POSIXct(paste(finaldata$Date, finaldata$Time), format = "%Y-%m-%d %H:%M:%S")
png("plot2.png", width=480, height=480, units="px")
plot(datetime, finaldata$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", type="l")
dev.off()
