setwd("setwd("C:/Users/Debanjan/Desktop/Coursera")")
fulldata <- read.csv("household_power_consumption.txt", head=TRUE, sep=";", na.strings="?")
Date <- as.Date(fulldata$Date, "%d/%m/%Y")
data <- cbind(Date, fulldata)
data <- data[,-2]
data201 <- subset(data, Date == "2007-02-01")
data202 <- subset(data, Date == "2007-02-02")
finaldata <- rbind(data201, data202)
datetime <- as.POSIXct(paste(finaldata$Date, finaldata$Time), format = "%Y-%m-%d %H:%M:%S")
png("plot4.png", width=480, height=480, units="px")
par(mfrow=c(2,2))
## plot(a)
plot(datetime, finaldata$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", type="l")
##plot(b)
plot(datetime, finaldata$Voltage, ylab="Voltage", type="l")
##plot(c)
plot(datetime, finaldata$Sub_metering_1, ylab="Energy sub metering", xlab="", type="l")
lines(datetime, finaldata$Sub_metering_2, col="red")
lines(datetime, finaldata$Sub_metering_3, col="blue")
legend("topright", lty=1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.9, bty="n")
##plot(d)
plot(datetime, finaldata$Global_reactive_power, ylab="Global_reactive_power", type="l")
dev.off()

